xgb_params:
  objective: "multi:softmax"
  num_class: 5
  learning_rate: 0.1
  max_depth: 6
  min_child_weight: 3
  subsample: 0.8
  colsample_bytree: 0.8
  gamma: 0.1
  reg_alpha: 0.1
  reg_lambda: 0.1
  eval_metric: "mlogloss"

train_params:
  num_boost_round: 1000